package com.ray.p2p.mapper.loan;

import com.ray.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * 获取历史平均年化收益率
     *
     * @param
     * @return java.lang.Double
     */
    Double selectHistoryAverageRate();

    /**
     * 分页查询产品信息列表
     *
     * @param paramMap
     * @return java.util.List<com.ray.p2p.model.loan.LoanInfo>
     */
    List<LoanInfo> selectLoanInfoByPage(Map<String, Object> paramMap);


    /**
     * 根据产品类型查询产品的总记录数
     *
     * @param paramMap
     * @return java.lang.Long
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 更新产品的剩余可投金额
     *
     * @param paramMap
     * @return int
     */
    int updateLeftProductMoneyByInvest(Map<String, Object> paramMap);

    /**
     * 根据产品状态获取产品信息列表
     *
     * @param productStatus
     * @return java.util.List<com.ray.p2p.model.loan.LoanInfo>
     */
    List<LoanInfo> selectLoanInfoListByProductStatus(Integer productStatus);
}