package com.ray.p2p.mapper.user;

import com.ray.p2p.model.user.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user
     *
     * @mbggenerated Sat May 15 11:05:12 CST 2020
     */
    int updateByPrimaryKey(User record);

    /**
     * 获取平台注册总人数
     *
     * @param
     * @return java.lang.Long
     */
    Long selectAllUserCount();

    /**
     * 根据手机号查询用户信息
     *
     * @param phone
     * @return com.ray.p2p.model.user.User
     */
    User selectUserByPhone(String phone);

    /**
     * 根据用户的手机号和登录密码查询用户信息
     *
     * @param loginPassword
	 * @param phone
     * @return com.ray.p2p.model.user.User
     */
    User selectUserByPhoneAndLoginPassword(String loginPassword, String phone);
}